#version: '3.8'

services:
  clickhouse:
    container_name: 'clickhouse-server'
    image: 'clickhouse/clickhouse-server:${CLICKHOUSE_VERSION-25.6-alpine}'
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: 1
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - './.docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml'
      - './.docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml'

  clickhouse_tls:
    build:
      context: ./
      dockerfile: .docker/clickhouse_tls/Dockerfile
    container_name: 'clickhouse-server-tls'
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: 1
    ports:
      - '8443:8443'
      - '9440:9440'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - './.docker/clickhouse_tls/config.xml:/etc/clickhouse-server/config.xml'
      - './.docker/clickhouse_tls/users.xml:/etc/clickhouse-server/users.xml'
